import os
from pathlib import Path
import json

from BD.orchestrator import analyze_diving_phase, analyze_stroke, analyze_split_times, stroke_stage_bbfs, stroke_stage_bs, stroke_plot_bs

def quick_analyze(video_name):
    # final_output_path = The .txt file generated by step 2
    final_output_path = f"/home/kady6582/SwimAnalysisPro/test_outputs/keypoints/{video_name}.txt"
    video_path = f"/home/kady6582/SwimAnalysisPro/demo_debug_videos/{video_name}.mp4"
    style_model_path = "/home/kady6582/SwimAnalysisPro/data/models/svm_model_new_3.pkl"
    
    print(f"--- Quick Analyze for {video_name} ---")
    if not os.path.exists(final_output_path):
        print("No .txt file found!")
        return

    # Step 3
    print("Step 3: Diving phase...")
    diving_analysis_result = analyze_diving_phase(video_path, final_output_path)
    segments = diving_analysis_result.get("segments", [])
    s1, e1 = segments[0] if len(segments) > 0 else (None, None)
    s2, e2 = segments[1] if len(segments) > 1 else (None, None)
    waterline_y = diving_analysis_result["waterline_y"]
    touch_frame = diving_analysis_result["touch_frame"]
    print(f"s1={s1}, e1={e1}, s2={s2}, e2={e2}, len={len(segments)}")

    # Step 4
    print("Step 4: Stroke Style...")
    stroke_label_int = analyze_stroke(video_path, final_output_path, style_model_path)
    label_dict = {0: "backstroke", 1: "breaststroke", 2: "freestyle", 3: "butterfly"}
    stroke_style = label_dict.get(stroke_label_int, "freestyle")
    print(f"Recognized: {stroke_style}")

    # Step 5
    print("Step 5: Phase analysis...")
    phase_output_path = f"/home/kady6582/SwimAnalysisPro/test_outputs/Stroke_Phase_Frames/{video_name}_a.txt"
    laps_data = diving_analysis_result.get("laps_data")
    
    analysis_output = stroke_stage_bbfs.run_backstroke_butterfly_analysis(
        txt_path=final_output_path,
        video_path=video_path,
        waterline_y=waterline_y,
        laps_data=laps_data,
        output_txt_path=phase_output_path
    )
    print(f"Step 5 returned: {analysis_output['status']}")
    
    if analysis_output['status'] != 'success':
        print(f"Reason: {analysis_output.get('reason')}")
        
    print("Step 6: Split times...")
    import cv2
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    cap.release()

    passed, total_time, split_breakdown, lap_durations = analyze_split_times(
        final_output_path, s1, fps, width * 0.4, width * 0.05, width - 60, laps_data=laps_data
    )
    print(f"total_time: {total_time}")

    print("DONE QUICK ANALYZE")

if __name__ == '__main__':
    quick_analyze("real_time_picture (434)")
